'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wsprod1.facturehoy.com:80/CFDI/WsEmisionTimbrado")>  _
        Public ReadOnly Property erp_neogenis_FactureHoyNT_WsEmisionTimbradoService() As String
            Get
                Return CType(Me("erp_neogenis_FactureHoyNT_WsEmisionTimbradoService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wsprod1.facturehoy.com:80/CFDI/WsServicios")>  _
        Public ReadOnly Property erp_neogenis_FactureHoyObtenerServiciosProducccion_WsServiciosService() As String
            Get
                Return CType(Me("erp_neogenis_FactureHoyObtenerServiciosProducccion_WsServiciosService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.facturehoy.com:80/CFDI/WsEmisionTimbrado")>  _
        Public ReadOnly Property erp_neogenis_FactureHoyCancelaOtroPAC_WsEmisionTimbradoService() As String
            Get
                Return CType(Me("erp_neogenis_FactureHoyCancelaOtroPAC_WsEmisionTimbradoService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://cancelacion.facturehoy.com:80/CancelacionCFDI33/WsCancelacionCFDI33")>  _
        Public ReadOnly Property erp_neogenis_WsCancelacionFHCFDI33_WsCancelacionCFDI33() As String
            Get
                Return CType(Me("erp_neogenis_WsCancelacionFHCFDI33_WsCancelacionCFDI33"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://sat.sifei.com.mx:8443/SIFEI/SIFEI")>  _
        Public ReadOnly Property erp_neogenis_SIFEI33_SIFEIService() As String
            Get
                Return CType(Me("erp_neogenis_SIFEI33_SIFEIService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://sat.sifei.com.mx:9000/CancelacionSIFEI/Cancelacion")>  _
        Public ReadOnly Property erp_neogenis_CancelacionSIFEI_Cancelacion() As String
            Get
                Return CType(Me("erp_neogenis_CancelacionSIFEI_Cancelacion"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://devcfdi.sifei.com.mx:8888/CancelacionSIFEI/Cancelacion")>  _
        Public ReadOnly Property erp_neogenis_CancelacionPruebasSIFEI_Cancelacion() As String
            Get
                Return CType(Me("erp_neogenis_CancelacionPruebasSIFEI_Cancelacion"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://devcfdi.sifei.com.mx:8080/SIFEI33/SIFEI")>  _
        Public ReadOnly Property erp_neogenis_SIFEI33Pruebas_SIFEIService() As String
            Get
                Return CType(Me("erp_neogenis_SIFEI33Pruebas_SIFEIService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://devcfdi.sifei.com.mx:8080/SIFEI33/SIFEI")>  _
        Public ReadOnly Property erp_neogenis_SIFEIPruebas_SIFEIService() As String
            Get
                Return CType(Me("erp_neogenis_SIFEIPruebas_SIFEIService"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.erp_neogenis.My.MySettings
            Get
                Return Global.erp_neogenis.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
