'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WsCancelacionFHCFDI33
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WsCancelacionCFDI33PortBinding", [Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class WsCancelacionCFDI33
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ObtienePeticionesPendientesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtieneStatusCFDIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtieneRelacionadosCFDIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtieneRelacionadosCFDICAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarCFDIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AceptarRechazarCancelacionCAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarCFDICAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AceptarRechazarCancelacionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.erp_neogenis.My.MySettings.Default.erp_neogenis_WsCancelacionFHCFDI33_WsCancelacionCFDI33
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ObtienePeticionesPendientesCompleted As ObtienePeticionesPendientesCompletedEventHandler
        
        '''<remarks/>
        Public Event ObtieneStatusCFDICompleted As ObtieneStatusCFDICompletedEventHandler
        
        '''<remarks/>
        Public Event ObtieneRelacionadosCFDICompleted As ObtieneRelacionadosCFDICompletedEventHandler
        
        '''<remarks/>
        Public Event ObtieneRelacionadosCFDICACompleted As ObtieneRelacionadosCFDICACompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarCFDICompleted As CancelarCFDICompletedEventHandler
        
        '''<remarks/>
        Public Event AceptarRechazarCancelacionCACompleted As AceptarRechazarCancelacionCACompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarCFDICACompleted As CancelarCFDICACompletedEventHandler
        
        '''<remarks/>
        Public Event AceptarRechazarCancelacionCompleted As AceptarRechazarCancelacionCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtienePeticionesPendientes(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idServicio As Integer, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal RfcReceptor As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsResponsePendientesBO
            Dim results() As Object = Me.Invoke("ObtienePeticionesPendientes", New Object() {usuario, contrasenia, idServicio, RfcReceptor})
            Return CType(results(0),wsResponsePendientesBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtienePeticionesPendientesAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String)
            Me.ObtienePeticionesPendientesAsync(usuario, contrasenia, idServicio, RfcReceptor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtienePeticionesPendientesAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String, ByVal userState As Object)
            If (Me.ObtienePeticionesPendientesOperationCompleted Is Nothing) Then
                Me.ObtienePeticionesPendientesOperationCompleted = AddressOf Me.OnObtienePeticionesPendientesOperationCompleted
            End If
            Me.InvokeAsync("ObtienePeticionesPendientes", New Object() {usuario, contrasenia, idServicio, RfcReceptor}, Me.ObtienePeticionesPendientesOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtienePeticionesPendientesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtienePeticionesPendientesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtienePeticionesPendientesCompleted(Me, New ObtienePeticionesPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtieneStatusCFDI(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idServicio As Integer, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal xml() As Byte) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsResponseStatusBO
            Dim results() As Object = Me.Invoke("ObtieneStatusCFDI", New Object() {usuario, contrasenia, idServicio, xml})
            Return CType(results(0),wsResponseStatusBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtieneStatusCFDIAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte)
            Me.ObtieneStatusCFDIAsync(usuario, contrasenia, idServicio, xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtieneStatusCFDIAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte, ByVal userState As Object)
            If (Me.ObtieneStatusCFDIOperationCompleted Is Nothing) Then
                Me.ObtieneStatusCFDIOperationCompleted = AddressOf Me.OnObtieneStatusCFDIOperationCompleted
            End If
            Me.InvokeAsync("ObtieneStatusCFDI", New Object() {usuario, contrasenia, idServicio, xml}, Me.ObtieneStatusCFDIOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtieneStatusCFDIOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtieneStatusCFDICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtieneStatusCFDICompleted(Me, New ObtieneStatusCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtieneRelacionadosCFDI(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idServicio As Integer, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal RfcReceptor As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal UUID As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal certificado() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal RSAPK As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsResponseRelacionadosBO
            Dim results() As Object = Me.Invoke("ObtieneRelacionadosCFDI", New Object() {usuario, contrasenia, idServicio, RfcReceptor, UUID, certificado, RSAPK})
            Return CType(results(0),wsResponseRelacionadosBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtieneRelacionadosCFDIAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String, ByVal UUID As String, ByVal certificado() As Byte, ByVal RSAPK As String)
            Me.ObtieneRelacionadosCFDIAsync(usuario, contrasenia, idServicio, RfcReceptor, UUID, certificado, RSAPK, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtieneRelacionadosCFDIAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String, ByVal UUID As String, ByVal certificado() As Byte, ByVal RSAPK As String, ByVal userState As Object)
            If (Me.ObtieneRelacionadosCFDIOperationCompleted Is Nothing) Then
                Me.ObtieneRelacionadosCFDIOperationCompleted = AddressOf Me.OnObtieneRelacionadosCFDIOperationCompleted
            End If
            Me.InvokeAsync("ObtieneRelacionadosCFDI", New Object() {usuario, contrasenia, idServicio, RfcReceptor, UUID, certificado, RSAPK}, Me.ObtieneRelacionadosCFDIOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtieneRelacionadosCFDIOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtieneRelacionadosCFDICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtieneRelacionadosCFDICompleted(Me, New ObtieneRelacionadosCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtieneRelacionadosCFDICA(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idServicio As Integer, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal RfcReceptor As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal UUID As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsResponseRelacionadosBO
            Dim results() As Object = Me.Invoke("ObtieneRelacionadosCFDICA", New Object() {usuario, contrasenia, idServicio, RfcReceptor, UUID})
            Return CType(results(0),wsResponseRelacionadosBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtieneRelacionadosCFDICAAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String, ByVal UUID As String)
            Me.ObtieneRelacionadosCFDICAAsync(usuario, contrasenia, idServicio, RfcReceptor, UUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtieneRelacionadosCFDICAAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String, ByVal UUID As String, ByVal userState As Object)
            If (Me.ObtieneRelacionadosCFDICAOperationCompleted Is Nothing) Then
                Me.ObtieneRelacionadosCFDICAOperationCompleted = AddressOf Me.OnObtieneRelacionadosCFDICAOperationCompleted
            End If
            Me.InvokeAsync("ObtieneRelacionadosCFDICA", New Object() {usuario, contrasenia, idServicio, RfcReceptor, UUID}, Me.ObtieneRelacionadosCFDICAOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtieneRelacionadosCFDICAOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtieneRelacionadosCFDICACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtieneRelacionadosCFDICACompleted(Me, New ObtieneRelacionadosCFDICACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelarCFDI(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idServicio As Integer, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal xml() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal certificado() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal RSAPK As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal email As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsResponseCancelacionBO
            Dim results() As Object = Me.Invoke("CancelarCFDI", New Object() {usuario, contrasenia, idServicio, xml, certificado, RSAPK, email})
            Return CType(results(0),wsResponseCancelacionBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarCFDIAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte, ByVal certificado() As Byte, ByVal RSAPK As String, ByVal email As String)
            Me.CancelarCFDIAsync(usuario, contrasenia, idServicio, xml, certificado, RSAPK, email, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarCFDIAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte, ByVal certificado() As Byte, ByVal RSAPK As String, ByVal email As String, ByVal userState As Object)
            If (Me.CancelarCFDIOperationCompleted Is Nothing) Then
                Me.CancelarCFDIOperationCompleted = AddressOf Me.OnCancelarCFDIOperationCompleted
            End If
            Me.InvokeAsync("CancelarCFDI", New Object() {usuario, contrasenia, idServicio, xml, certificado, RSAPK, email}, Me.CancelarCFDIOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarCFDIOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarCFDICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarCFDICompleted(Me, New CancelarCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AceptarRechazarCancelacionCA(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idServicio As Integer, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal RfcReceptor As String, <System.Xml.Serialization.XmlElementAttribute("UUID", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)> ByVal UUID() As uuid) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsResponseAceptaRechazoBO
            Dim results() As Object = Me.Invoke("AceptarRechazarCancelacionCA", New Object() {usuario, contrasenia, idServicio, RfcReceptor, UUID})
            Return CType(results(0),wsResponseAceptaRechazoBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AceptarRechazarCancelacionCAAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String, ByVal UUID() As uuid)
            Me.AceptarRechazarCancelacionCAAsync(usuario, contrasenia, idServicio, RfcReceptor, UUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AceptarRechazarCancelacionCAAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String, ByVal UUID() As uuid, ByVal userState As Object)
            If (Me.AceptarRechazarCancelacionCAOperationCompleted Is Nothing) Then
                Me.AceptarRechazarCancelacionCAOperationCompleted = AddressOf Me.OnAceptarRechazarCancelacionCAOperationCompleted
            End If
            Me.InvokeAsync("AceptarRechazarCancelacionCA", New Object() {usuario, contrasenia, idServicio, RfcReceptor, UUID}, Me.AceptarRechazarCancelacionCAOperationCompleted, userState)
        End Sub
        
        Private Sub OnAceptarRechazarCancelacionCAOperationCompleted(ByVal arg As Object)
            If (Not (Me.AceptarRechazarCancelacionCACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AceptarRechazarCancelacionCACompleted(Me, New AceptarRechazarCancelacionCACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelarCFDICA(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idServicio As Integer, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal xml() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal email As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsResponseCancelacionBO
            Dim results() As Object = Me.Invoke("CancelarCFDICA", New Object() {usuario, contrasenia, idServicio, xml, email})
            Return CType(results(0),wsResponseCancelacionBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarCFDICAAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte, ByVal email As String)
            Me.CancelarCFDICAAsync(usuario, contrasenia, idServicio, xml, email, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarCFDICAAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte, ByVal email As String, ByVal userState As Object)
            If (Me.CancelarCFDICAOperationCompleted Is Nothing) Then
                Me.CancelarCFDICAOperationCompleted = AddressOf Me.OnCancelarCFDICAOperationCompleted
            End If
            Me.InvokeAsync("CancelarCFDICA", New Object() {usuario, contrasenia, idServicio, xml, email}, Me.CancelarCFDICAOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarCFDICAOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarCFDICACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarCFDICACompleted(Me, New CancelarCFDICACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://cfdi.ws2.facturehoy.certus.com/", ResponseNamespace:="http://cfdi.ws2.facturehoy.certus.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AceptarRechazarCancelacion(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasenia As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idServicio As Integer, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal RfcReceptor As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> ByVal certificado() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal RSAPK As String, <System.Xml.Serialization.XmlElementAttribute("UUID", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)> ByVal UUID() As uuid) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsResponseAceptaRechazoBO
            Dim results() As Object = Me.Invoke("AceptarRechazarCancelacion", New Object() {usuario, contrasenia, idServicio, RfcReceptor, certificado, RSAPK, UUID})
            Return CType(results(0),wsResponseAceptaRechazoBO)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AceptarRechazarCancelacionAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String, ByVal certificado() As Byte, ByVal RSAPK As String, ByVal UUID() As uuid)
            Me.AceptarRechazarCancelacionAsync(usuario, contrasenia, idServicio, RfcReceptor, certificado, RSAPK, UUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AceptarRechazarCancelacionAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal RfcReceptor As String, ByVal certificado() As Byte, ByVal RSAPK As String, ByVal UUID() As uuid, ByVal userState As Object)
            If (Me.AceptarRechazarCancelacionOperationCompleted Is Nothing) Then
                Me.AceptarRechazarCancelacionOperationCompleted = AddressOf Me.OnAceptarRechazarCancelacionOperationCompleted
            End If
            Me.InvokeAsync("AceptarRechazarCancelacion", New Object() {usuario, contrasenia, idServicio, RfcReceptor, certificado, RSAPK, UUID}, Me.AceptarRechazarCancelacionOperationCompleted, userState)
        End Sub
        
        Private Sub OnAceptarRechazarCancelacionOperationCompleted(ByVal arg As Object)
            If (Not (Me.AceptarRechazarCancelacionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AceptarRechazarCancelacionCompleted(Me, New AceptarRechazarCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsResponsePendientesBO
        
        Private codigoErrorField As Integer
        
        Private isErrorField As Boolean
        
        Private mensajeField As String
        
        Private pendientesField() As Byte
        
        Private statusField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoError() As Integer
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property isError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property pendientes() As Byte()
            Get
                Return Me.pendientesField
            End Get
            Set
                Me.pendientesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsResponseAceptaRechazoBO
        
        Private codigoErrorField As Integer
        
        Private isErrorField As Boolean
        
        Private mensajeField As String
        
        Private respuestaField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoError() As Integer
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property isError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property respuesta() As Byte()
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class uuid
        
        Private respuestaField As String
        
        Private uuid1Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property respuesta() As String
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("uuid", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property uuid1() As String
            Get
                Return Me.uuid1Field
            End Get
            Set
                Me.uuid1Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsResponseCancelacionBO
        
        Private acuseField() As Byte
        
        Private codigoErrorField As Integer
        
        Private esCancelableField As String
        
        Private estadoField As String
        
        Private estatusCancelacionField As String
        
        Private isErrorField As Boolean
        
        Private isErrorFieldSpecified As Boolean
        
        Private mensajeField As String
        
        Private rutaDescargaAcuseField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property acuse() As Byte()
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoError() As Integer
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property esCancelable() As String
            Get
                Return Me.esCancelableField
            End Get
            Set
                Me.esCancelableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estatusCancelacion() As String
            Get
                Return Me.estatusCancelacionField
            End Get
            Set
                Me.estatusCancelacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property isError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property isErrorSpecified() As Boolean
            Get
                Return Me.isErrorFieldSpecified
            End Get
            Set
                Me.isErrorFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property rutaDescargaAcuse() As String
            Get
                Return Me.rutaDescargaAcuseField
            End Get
            Set
                Me.rutaDescargaAcuseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsResponseRelacionadosBO
        
        Private codigoErrorField As Integer
        
        Private isErrorField As Boolean
        
        Private mensajeField As String
        
        Private respuestaField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoError() As Integer
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property isError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property respuesta() As Byte()
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsResponseStatusBO
        
        Private codigoErrorField As Integer
        
        Private isErrorField As Boolean
        
        Private mensajeField As String
        
        Private respuestaField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoError() As Integer
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property isError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property respuesta() As Byte()
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub ObtienePeticionesPendientesCompletedEventHandler(ByVal sender As Object, ByVal e As ObtienePeticionesPendientesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtienePeticionesPendientesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsResponsePendientesBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsResponsePendientesBO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub ObtieneStatusCFDICompletedEventHandler(ByVal sender As Object, ByVal e As ObtieneStatusCFDICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtieneStatusCFDICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsResponseStatusBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsResponseStatusBO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub ObtieneRelacionadosCFDICompletedEventHandler(ByVal sender As Object, ByVal e As ObtieneRelacionadosCFDICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtieneRelacionadosCFDICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsResponseRelacionadosBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsResponseRelacionadosBO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub ObtieneRelacionadosCFDICACompletedEventHandler(ByVal sender As Object, ByVal e As ObtieneRelacionadosCFDICACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtieneRelacionadosCFDICACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsResponseRelacionadosBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsResponseRelacionadosBO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub CancelarCFDICompletedEventHandler(ByVal sender As Object, ByVal e As CancelarCFDICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarCFDICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsResponseCancelacionBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsResponseCancelacionBO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub AceptarRechazarCancelacionCACompletedEventHandler(ByVal sender As Object, ByVal e As AceptarRechazarCancelacionCACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AceptarRechazarCancelacionCACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsResponseAceptaRechazoBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsResponseAceptaRechazoBO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub CancelarCFDICACompletedEventHandler(ByVal sender As Object, ByVal e As CancelarCFDICACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarCFDICACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsResponseCancelacionBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsResponseCancelacionBO)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub AceptarRechazarCancelacionCompletedEventHandler(ByVal sender As Object, ByVal e As AceptarRechazarCancelacionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AceptarRechazarCancelacionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsResponseAceptaRechazoBO
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsResponseAceptaRechazoBO)
            End Get
        End Property
    End Class
End Namespace
