'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Resource", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to logo_union.jpg.
        '''</summary>
        Friend Shared ReadOnly Property AppBanner() As String
            Get
                Return ResourceManager.GetString("AppBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar Cliente.
        '''</summary>
        Friend Shared ReadOnly Property btnAddClient() As String
            Get
                Return ResourceManager.GetString("btnAddClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar Concepto.
        '''</summary>
        Friend Shared ReadOnly Property btnAddItem() As String
            Get
                Return ResourceManager.GetString("btnAddItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar Producto.
        '''</summary>
        Friend Shared ReadOnly Property btnAddProduct() As String
            Get
                Return ResourceManager.GetString("btnAddProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelar operación.
        '''</summary>
        Friend Shared ReadOnly Property btnCancelInvoice() As String
            Get
                Return ResourceManager.GetString("btnCancelInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generar CFDI.
        '''</summary>
        Friend Shared ReadOnly Property btnCreateInvoice() As String
            Get
                Return ResourceManager.GetString("btnCreateInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property btnEnvCancel() As String
            Get
                Return ResourceManager.GetString("btnEnvCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardar.
        '''</summary>
        Friend Shared ReadOnly Property btnEnvSaveClient() As String
            Get
                Return ResourceManager.GetString("btnEnvSaveClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardar.
        '''</summary>
        Friend Shared ReadOnly Property btnSave() As String
            Get
                Return ResourceManager.GetString("btnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro que desea borrar este certificado?.
        '''</summary>
        Friend Shared ReadOnly Property CertificateDeleteConfirmationMessage() As String
            Get
                Return ResourceManager.GetString("CertificateDeleteConfirmationMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen Certificados registrados.
        '''</summary>
        Friend Shared ReadOnly Property certificatesEmptyGridMessage() As String
            Get
                Return ResourceManager.GetString("certificatesEmptyGridMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro que desea borrar a este cliente de la base de datos?.
        '''</summary>
        Friend Shared ReadOnly Property ClientsDeleteConfirmationMessage() As String
            Get
                Return ResourceManager.GetString("ClientsDeleteConfirmationMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen clientes registrados.
        '''</summary>
        Friend Shared ReadOnly Property ClientsEmptyGridMessage() As String
            Get
                Return ResourceManager.GetString("ClientsEmptyGridMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- Seleccione --.
        '''</summary>
        Friend Shared ReadOnly Property cmbEmptyMessage() As String
            Get
                Return ResourceManager.GetString("cmbEmptyMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activo.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameActive() As String
            Get
                Return ResourceManager.GetString("gridColumnNameActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importe.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameAmount() As String
            Get
                Return ResourceManager.GetString("gridColumnNameAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certificado.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameCertificate() As String
            Get
                Return ResourceManager.GetString("gridColumnNameCertificate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código-Sku.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameCode() As String
            Get
                Return ResourceManager.GetString("gridColumnNameCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre Comercial.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameComercialName() As String
            Get
                Return ResourceManager.GetString("gridColumnNameComercialName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contacto.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameContact() As String
            Get
                Return ResourceManager.GetString("gridColumnNameContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teléfono del Contacto.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameContactPhone() As String
            Get
                Return ResourceManager.GetString("gridColumnNameContactPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameDelete() As String
            Get
                Return ResourceManager.GetString("gridColumnNameDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descripción.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameDescription() As String
            Get
                Return ResourceManager.GetString("gridColumnNameDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descargar.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameDownload() As String
            Get
                Return ResourceManager.GetString("gridColumnNameDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unidad.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameMeasureUnit() As String
            Get
                Return ResourceManager.GetString("gridColumnNameMeasureUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cantidad.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameQuantity() As String
            Get
                Return ResourceManager.GetString("gridColumnNameQuantity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RFC.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameRFC() As String
            Get
                Return ResourceManager.GetString("gridColumnNameRFC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Razón Social.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameSocialReason() As String
            Get
                Return ResourceManager.GetString("gridColumnNameSocialReason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precio Unit. 1.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameUnitaryPrice() As String
            Get
                Return ResourceManager.GetString("gridColumnNameUnitaryPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precio Unit. 2.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameUnitaryPrice2() As String
            Get
                Return ResourceManager.GetString("gridColumnNameUnitaryPrice2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precio Unit. 3.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameUnitaryPrice3() As String
            Get
                Return ResourceManager.GetString("gridColumnNameUnitaryPrice3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precio Unit. 4.
        '''</summary>
        Friend Shared ReadOnly Property gridColumnNameUnitaryPrice4() As String
            Get
                Return ResourceManager.GetString("gridColumnNameUnitaryPrice4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extensión Inválida.
        '''</summary>
        Friend Shared ReadOnly Property InvalidExtension() As String
            Get
                Return ResourceManager.GetString("InvalidExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro que desea borrar este concepto?.
        '''</summary>
        Friend Shared ReadOnly Property ItemsDeleteConfirmationMessage() As String
            Get
                Return ResourceManager.GetString("ItemsDeleteConfirmationMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen conceptos registrados.
        '''</summary>
        Friend Shared ReadOnly Property ItemsEmptyGridMessage() As String
            Get
                Return ResourceManager.GetString("ItemsEmptyGridMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activo:.
        '''</summary>
        Friend Shared ReadOnly Property lblActivate() As String
            Get
                Return ResourceManager.GetString("lblActivate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certificado:.
        '''</summary>
        Friend Shared ReadOnly Property lblCertificate() As String
            Get
                Return ResourceManager.GetString("lblCertificate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuración de Certificados.
        '''</summary>
        Friend Shared ReadOnly Property lblCertificateLegend() As String
            Get
                Return ResourceManager.GetString("lblCertificateLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lista de Certificados.
        '''</summary>
        Friend Shared ReadOnly Property lblCertificatesListLegend() As String
            Get
                Return ResourceManager.GetString("lblCertificatesListLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datos del Cliente.
        '''</summary>
        Friend Shared ReadOnly Property lblClientData() As String
            Get
                Return ResourceManager.GetString("lblClientData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar/Editar Cliente.
        '''</summary>
        Friend Shared ReadOnly Property lblClientEditLegend() As String
            Get
                Return ResourceManager.GetString("lblClientEditLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar Conceptos.
        '''</summary>
        Friend Shared ReadOnly Property lblClientItems() As String
            Get
                Return ResourceManager.GetString("lblClientItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Listado de Clientes.
        '''</summary>
        Friend Shared ReadOnly Property lblClientsListLegend() As String
            Get
                Return ResourceManager.GetString("lblClientsListLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datos del comprobante.
        '''</summary>
        Friend Shared ReadOnly Property lblClientsSelectionLegend() As String
            Get
                Return ResourceManager.GetString("lblClientsSelectionLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código-Sku:.
        '''</summary>
        Friend Shared ReadOnly Property lblCode() As String
            Get
                Return ResourceManager.GetString("lblCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colonia:.
        '''</summary>
        Friend Shared ReadOnly Property lblColony() As String
            Get
                Return ResourceManager.GetString("lblColony", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contacto:.
        '''</summary>
        Friend Shared ReadOnly Property lblContact() As String
            Get
                Return ResourceManager.GetString("lblContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email del Contacto:.
        '''</summary>
        Friend Shared ReadOnly Property lblContactEmail() As String
            Get
                Return ResourceManager.GetString("lblContactEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teléfono del Contacto:.
        '''</summary>
        Friend Shared ReadOnly Property lblContactPhone() As String
            Get
                Return ResourceManager.GetString("lblContactPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to País:.
        '''</summary>
        Friend Shared ReadOnly Property lblCountry() As String
            Get
                Return ResourceManager.GetString("lblCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuración de Datos de la Empresa.
        '''</summary>
        Friend Shared ReadOnly Property lblDataLegend() As String
            Get
                Return ResourceManager.GetString("lblDataLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar / Editar Datos de Envío.
        '''</summary>
        Friend Shared ReadOnly Property lblDatosEnvioLegend() As String
            Get
                Return ResourceManager.GetString("lblDatosEnvioLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descripción:.
        '''</summary>
        Friend Shared ReadOnly Property lblDescription() As String
            Get
                Return ResourceManager.GetString("lblDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enviar a:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnviarA() As String
            Get
                Return ResourceManager.GetString("lblEnviarA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calle:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioCalle() As String
            Get
                Return ResourceManager.GetString("lblEnvioCalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colonia:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioColonia() As String
            Get
                Return ResourceManager.GetString("lblEnvioColonia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código Postal:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioCP() As String
            Get
                Return ResourceManager.GetString("lblEnvioCP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioEmail() As String
            Get
                Return ResourceManager.GetString("lblEnvioEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioEstado() As String
            Get
                Return ResourceManager.GetString("lblEnvioEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Municipio:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioMunicipio() As String
            Get
                Return ResourceManager.GetString("lblEnvioMunicipio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Ext.:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioNoExt() As String
            Get
                Return ResourceManager.GetString("lblEnvioNoExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Int.:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioNoInt() As String
            Get
                Return ResourceManager.GetString("lblEnvioNoInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioNombre() As String
            Get
                Return ResourceManager.GetString("lblEnvioNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to País:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioPais() As String
            Get
                Return ResourceManager.GetString("lblEnvioPais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teléfono:.
        '''</summary>
        Friend Shared ReadOnly Property lblEnvioTelefono() As String
            Get
                Return ResourceManager.GetString("lblEnvioTelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Ext..
        '''</summary>
        Friend Shared ReadOnly Property lblExtNumber() As String
            Get
                Return ResourceManager.GetString("lblExtNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importe Tasa 0%:.
        '''</summary>
        Friend Shared ReadOnly Property lblImporteTasaCero() As String
            Get
                Return ResourceManager.GetString("lblImporteTasaCero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Int..
        '''</summary>
        Friend Shared ReadOnly Property lblIntNumber() As String
            Get
                Return ResourceManager.GetString("lblIntNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conceptos.
        '''</summary>
        Friend Shared ReadOnly Property lblItems() As String
            Get
                Return ResourceManager.GetString("lblItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IVA = .
        '''</summary>
        Friend Shared ReadOnly Property lblIVA() As String
            Get
                Return ResourceManager.GetString("lblIVA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logo para portal:.
        '''</summary>
        Friend Shared ReadOnly Property lblLogo() As String
            Get
                Return ResourceManager.GetString("lblLogo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logo Actual:.
        '''</summary>
        Friend Shared ReadOnly Property lblLogoActual() As String
            Get
                Return ResourceManager.GetString("lblLogoActual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lugar de expedición:.
        '''</summary>
        Friend Shared ReadOnly Property lblLugarExpedicion() As String
            Get
                Return ResourceManager.GetString("lblLugarExpedicion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Método de pago:.
        '''</summary>
        Friend Shared ReadOnly Property lblMetodoPago() As String
            Get
                Return ResourceManager.GetString("lblMetodoPago", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número de cuenta: (opcional).
        '''</summary>
        Friend Shared ReadOnly Property lblNumCtaPago() As String
            Get
                Return ResourceManager.GetString("lblNumCtaPago", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número de la cuenta con la cual se pagará esta factura (al menos los 4 últimos dígitos de la cuenta).
        '''</summary>
        Friend Shared ReadOnly Property lblNumCtaPagoTooltip() As String
            Get
                Return ResourceManager.GetString("lblNumCtaPagoTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contraseña:.
        '''</summary>
        Friend Shared ReadOnly Property lblPassword() As String
            Get
                Return ResourceManager.GetString("lblPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Llave Privada:.
        '''</summary>
        Friend Shared ReadOnly Property lblPrivateKey() As String
            Get
                Return ResourceManager.GetString("lblPrivateKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Llave Privada Descargable:.
        '''</summary>
        Friend Shared ReadOnly Property lblPrivateKeyDownload() As String
            Get
                Return ResourceManager.GetString("lblPrivateKeyDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuración de Llave Privada &amp; Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property lblPrivateKeyLegend() As String
            Get
                Return ResourceManager.GetString("lblPrivateKeyLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar/Editar Producto.
        '''</summary>
        Friend Shared ReadOnly Property lblProductEditLegend() As String
            Get
                Return ResourceManager.GetString("lblProductEditLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Listado de Productos.
        '''</summary>
        Friend Shared ReadOnly Property lblProductsListLegend() As String
            Get
                Return ResourceManager.GetString("lblProductsListLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cantidad:.
        '''</summary>
        Friend Shared ReadOnly Property lblQuantity() As String
            Get
                Return ResourceManager.GetString("lblQuantity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Régimen fiscal:.
        '''</summary>
        Friend Shared ReadOnly Property lblRegimen() As String
            Get
                Return ResourceManager.GetString("lblRegimen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reportes.
        '''</summary>
        Friend Shared ReadOnly Property lblReportsLegend() As String
            Get
                Return ResourceManager.GetString("lblReportsLegend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resumen.
        '''</summary>
        Friend Shared ReadOnly Property lblResume() As String
            Get
                Return ResourceManager.GetString("lblResume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RFC:.
        '''</summary>
        Friend Shared ReadOnly Property lblRFC() As String
            Get
                Return ResourceManager.GetString("lblRFC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Razón Social:.
        '''</summary>
        Friend Shared ReadOnly Property lblSocialReason() As String
            Get
                Return ResourceManager.GetString("lblSocialReason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado:.
        '''</summary>
        Friend Shared ReadOnly Property lblState() As String
            Get
                Return ResourceManager.GetString("lblState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calle:.
        '''</summary>
        Friend Shared ReadOnly Property lblStreet() As String
            Get
                Return ResourceManager.GetString("lblStreet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub Total = .
        '''</summary>
        Friend Shared ReadOnly Property lblSubTotal() As String
            Get
                Return ResourceManager.GetString("lblSubTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total =.
        '''</summary>
        Friend Shared ReadOnly Property lblTotal() As String
            Get
                Return ResourceManager.GetString("lblTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Municipio:.
        '''</summary>
        Friend Shared ReadOnly Property lblTownship() As String
            Get
                Return ResourceManager.GetString("lblTownship", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unidad de Medida:.
        '''</summary>
        Friend Shared ReadOnly Property lblUnit() As String
            Get
                Return ResourceManager.GetString("lblUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precio Unitario:.
        '''</summary>
        Friend Shared ReadOnly Property lblUnitaryPrice() As String
            Get
                Return ResourceManager.GetString("lblUnitaryPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código Postal:.
        '''</summary>
        Friend Shared ReadOnly Property lblZipCode() As String
            Get
                Return ResourceManager.GetString("lblZipCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro que desea borrar este producto de la base de datos?.
        '''</summary>
        Friend Shared ReadOnly Property ProductsDeleteConfirmationMessage() As String
            Get
                Return ResourceManager.GetString("ProductsDeleteConfirmationMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen productos registrados.
        '''</summary>
        Friend Shared ReadOnly Property ProductsEmptyGridMessage() As String
            Get
                Return ResourceManager.GetString("ProductsEmptyGridMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Va a borrar un proveedor de la Base de Datos. ¿Desea continuar?.
        '''</summary>
        Friend Shared ReadOnly Property ProviderDeleteConfirmationMessage() As String
            Get
                Return ResourceManager.GetString("ProviderDeleteConfirmationMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Requerido.
        '''</summary>
        Friend Shared ReadOnly Property validatorMessage() As String
            Get
                Return ResourceManager.GetString("validatorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formato Inválido.
        '''</summary>
        Friend Shared ReadOnly Property validatorMessageEmail() As String
            Get
                Return ResourceManager.GetString("validatorMessageEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R.F.C. no válido.
        '''</summary>
        Friend Shared ReadOnly Property validatorMessageRfc() As String
            Get
                Return ResourceManager.GetString("validatorMessageRfc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sistema ERP Neogenis.
        '''</summary>
        Friend Shared ReadOnly Property WindowsTitle() As String
            Get
                Return ResourceManager.GetString("WindowsTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
